name: Artifacts
on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64]
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0
      - run: |
          zig build -Dtarget=x86_64-windows -Doptimize=ReleaseSafe
      - uses: actions/upload-artifact@v2
        with:
          name: upload ${{ matrix.os }}-${{ matrix.arch }}
          path: zig-out/bin/*
